SELECT FIRSTNAME, LASTNAME, SUM(ORDERQUANTITY) FROM FACTINTERNETSALES INNER JOIN DIMCUSTOMER AS DIMCUSTOMER ON FACTINTERNETSALES.CUSTOMERKEY = DIMCUSTOMER.CUSTOMERKEY GROUP BY ROLLUP (FIRSTNAME, LASTNAME);

SELECT SALESTERRITORYCOUNTRY, SALESTERRITORYREGION, SALESTERRITORYGROUP, SUM(ORDERQUANTITY) FROM FACTINTERNETSALES INNER JOIN DIMSALESTERRITORY AS DIMSALESTERRITORY ON FACTINTERNETSALES.SALESTERRITORYKEY = DIMSALESTERRITORY.SALESTERRITORYKEY GROUP BY ROLLUP (SALESTERRITORYGROUP, SALESTERRITORYCOUNTRY, SALESTERRITORYREGION);

SELECT ENGLISHMONTHNAME, SUM(ORDERQUANTITY) FROM FACTINTERNETSALES INNER JOIN DIMDATE AS DIMDATE ON FACTINTERNETSALES.ORDERDATEKEY = DIMDATE.DATEKEY WHERE DAYNUMBEROFWEEK=1 GROUP BY ENGLISHMONTHNAME;
